package com.pwc.grading.masterdata.dao;

/**
 * A class consists all the database queries related to the master data management.
 *
 */
public class MasterDatatQueryConstants {
	public static final String DATA_BASE_PLACE_HOLDER = "#$DataBaseName#$";

	// ProgressMeter
	public static final String SELECT_PARTNER_IDS_BY_PROJECT_ID = "SELECT DISTINCT partnerId FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE projectId=?";
	public static final String SELECT_PARTNERS_BY_PARTNER_IDS = "SELECT * FROM #$DataBaseName#$.DBO.PARTNERDETAILS WHERE PARTNERID IN (?)";

	// PARTNER DETAILS
	public static final String INSERT_PARTNER = "INSERT INTO #$DataBaseName#$.DBO.PARTNERDETAILS VALUES(?,?,?)";
	public static final String SELECT_PARTNERS = "SELECT * FROM #$DataBaseName#$.DBO.PARTNERDETAILS";
	public static final String SELECT_PARTNER_BY_PARTNER_ID = "SELECT * FROM #$DataBaseName#$.DBO.PARTNERDETAILS WHERE PARTNERID=?";
	public static final String SELECT_PARTNER_BY_CLIENT_SPONSOR_ID = "SELECT * FROM #$DataBaseName#$.DBO.PARTNERDETAILS WHERE CLIENTSPONSORID=?";
	public static final String SELECT_PARTNER_BY_PARTNER_NAME = "SELECT * FROM #$DataBaseName#$.DBO.PARTNERDETAILS WHERE LOWER(PARTNERNAME)=?";
	public static final String SELECT_TOATL_PARTNER_COUNT = "SELECT count(*)  FROM #$DataBaseName#$.DBO.PARTNERDETAILS";

	// REMOVE THIS UPDATE PARTNER BY ID
	// public static final String UPDATE_PARTNER_BY_PARTNER_ID = "UPDATE
	// #$DataBaseName#$.DBO.PARTNERDETAILS SET PARTNERNAME=?,";

	// TRAINING CENTER DETAILS
	public static final String INSERT_TC_DETAIL = "INSERT INTO #$DataBaseName#$.DBO.TRAININGCENTERDETAILS VALUES(?,?,?,?,?,?,?,?,?)";
	public static final String SELECT_TC_BY_TC_ID_AND_PARTNER_ID = "SELECT * FROM #$DataBaseName#$.DBO.TRAININGCENTERDETAILS WHERE PARTNERID=? AND TCID=?";
	public static final String SELECT_TC_BY_TC_ID = "SELECT * FROM #$DataBaseName#$.DBO.TRAININGCENTERDETAILS WHERE  TCID=?";
	public static final String SELECT_TC_DETAILS = "SELECT * FROM #$DataBaseName#$.DBO.TRAININGCENTERDETAILS";
	public static final String SELECT_TC_DETAILS_BY_TC_IDS = "SELECT * FROM #$DataBaseName#$.DBO.TRAININGCENTERDETAILS WHERE TCID IN (?)";
	public static final String SELECT_TC_BY_PARTNER_ID = "SELECT * FROM #$DataBaseName#$.DBO.TRAININGCENTERDETAILS WHERE PARTNERID=?";

	// MASTER MAPPING DATA
	public static final String INSERT_MAPPING_DATA = "INSERT INTO #$DataBaseName#$.DBO.PROJECTMAPPINGDATA VALUES(?,?,?,?,?)";
	public static final String SELECT_MAPPING_DATA_BY_PARTNER_PROJECT_ID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE partnerProjectId=?";
	public static final String SELECT_MAPPING_DATA_BY_TC_ID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE TCID=?";
	public static final String SELECT_MAPPING_DATA_BY_PROJECT_MAPPING_ID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PROJECTMAPPINGID=?";
	public static final String SELECT_MAPPING_DATA = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA";
//	public static final String SELECT_MAPPING_DATA_BY_FIELD_AUDITOR_ID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA  WHERE FIELDAUDITORID=?";
	public static final String DELETE_PROJECT_MAPPING_BY_MAPPING_ID = "DELETE #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PROJECTMAPPINGID=?";
	public static final String UPDATE_MAPPING_DATA_BY_PROJECT_MAPPING_ID = "UPDATE #$DataBaseName#$.DBO.PROJECTMAPPINGDATA SET PARTNERPROJECTID=?,TCID=?,PROJECTID=?,PARTNERID=? WHERE PROJECTMAPPINGID=?";
	public static final String SELECT_MAPPING_DATA_BY_PROJECT_ID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PROJECTID=?";
	public static final String DELETE_PROJECT_MAPPING_BY_PROJECT_ID = "DELETE #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PROJECTID=?";
	
	// report
	public static final String SELECT_PARTNER_COUNT_BY_PROJECT_ID = "SELECT COUNT(DISTINCT PARTNERID) FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PROJECTID=?";
	public static final String SELECT_MAPPING_DATA_BY_TCID_AND_PROJECTID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PARTNERID=? AND TCID=? AND PROJECTID=?";
	public static final String SELECT_MAPPING_DATA_BY_PROJECT_ID_AND_PARTNER_ID = "SELECT * FROM #$DataBaseName#$.DBO.PROJECTMAPPINGDATA WHERE PROJECTID=? AND PARTNERID=?";

	// GradingEnable Table
	public static final String INSERT_GRADING_ENABLE = "INSERT INTO #$DataBaseName#$.DBO.GRADINGENABLE VALUES(?,?,?)";
	public static final String SELECT_GRADING_ENABLE_WHERE_PROJECTID_AND_PARTNERID = "SELECT * FROM #$DataBaseName#$.DBO.GRADINGENABLE WHERE PROJECTID=? AND PARTNERID=?";
	public static final String SELECT_GRADING_ENABLE_WHERE_PARTNERID = "SELECT * FROM #$DataBaseName#$.DBO.GRADINGENABLE WHERE PARTNERID=?";
	public static final String SELECT_GRADING_ENABLE_WHERE_PROJECT_ID = "SELECT * FROM #$DataBaseName#$.DBO.GRADINGENABLE WHERE PROJECTID=?";
	public static final String UPDATE_GRADING_ENABLE_WHERE_PROJECTID_AND_PARTNERID = "UPDATE #$DataBaseName#$.DBO.GRADINGENABLE SET ISGRADINGENABLE=? WHERE PROJECTID=? AND PARTNERID=?";
	public static final String DELETE_GRADING_ENABLE_WHERE_PROJECTID_AND_PARTNERID = "DELETE #$DataBaseName#$.DBO.GRADINGENABLE WHERE PROJECTID=? AND PARTNERID=?";
	public static final String DELETE_GRADING_ENABLE_WHERE_PROJECTID = "DELETE #$DataBaseName#$.DBO.GRADINGENABLE WHERE PROJECTID=?";
	
}
