package com.pwc.grading.surveyresponse.dao;

/**
 * A class contains all the database queries related to the Survey Response.
 *
 */
public class SurveyResponseQueryConstants {
	public static final String DATA_BASE_PLACE_HOLDER = "#$DataBaseName#$";
	public static final String INSERT_SURVEY_RESPONSE = "INSERT INTO #$DataBaseName#$.DBO.SURVEYRESPONSE VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String SELECT_SURVEY_RESPONSES = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE";
	public static final String SELECT_SURVEY_RESPONSE_BY_SURVEY_RESPONSE_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYRESPONSEID=?";
	public static final String DELETE_SURVEY_RESPONSE_BY_SURVEY_RESPONSE_ID = "DELETE FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYRESPONSEID=?";
	public static final String UPDATE_SURVEY_RESPONSE_BY_SURVEY_RESPONSE_ID = "UPDATE #$DataBaseName#$.DBO.SURVEYRESPONSE SET SURVEYID=?,USERID=?,SAVETIME=?,SUBMITTIME=?,RESPONDERTYPE=?,TOTALSCORE=?,ISSUBMITED=?,CENTERID=?,PARTNERID=?,AUDITFOR=?,AUDITFORID=?,MAXMARKS=?,SURVEYRESPONSEDATA=? WHERE SURVEYRESPONSEID=?";
	public static final String SELECT_SURVEY_RESPONSE_BY_SURVEY_ID_AND_USER_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND USERID=?";
	public static final String SELECT_SURVEY_RESPONSE_BY_USER_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE USERID=?";
	public static final String SELECT_SURVEY_RESPONSE_BY_SURVEY_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=?";
	public static final String DELETE_SURVEY_RESPONSE_BY_SURVEY_ID = "DELETE FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=?";

	public static final String SELECT_SURVEY_RESPONSE_BY_CENTER_ID_AND_SURVERY_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND CENTERID=?";
	public static final String DELETE_SURVEY_RESPONSE_BY_CENTER_ID_AND_SURVERY_ID = "DELETE #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND CENTERID=?";

	public static final String SELECT_SURVEY_RESPONSE_BY_PARTNER_ID_AND_SURVERY_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND PARTNERID=?";
	public static final String DELETE_SURVEY_RESPONSE_BY_PARTNER_ID_AND_SURVERY_ID = "DELETE #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND PARTNERID=?";

	public static final String SELECT_SURVEY_RESPONSE_BY_AUDIT_FOR_ID_ID_AND_SURVERY_ID = "SELECT * FROM #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND AUDITFOR=? AND AUDITFORID=?";
	public static final String DELETE_SURVEY_RESPONSE_BY_AUDIT_FOR_ID_ID_AND_SURVERY_ID = "DELETE #$DataBaseName#$.DBO.SURVEYRESPONSE WHERE SURVEYID=? AND AUDITFOR=? AND AUDITFORID=?";

	public static final String AUDIT_FOR_TRANING_CENTER = "trainingCenter";
	public static final String AUDIT_FOR_PARTNER = "partner";

}
